changed shebang to use /bin/sh have not tested scripts

diff --git a/bin/sssh b/bin/sssh
--- a/bin/sssh
+++ b/bin/sssh
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Name: sssh*
 # Author: sam.k.tan@oracle.com
@@ -11,38 +11,38 @@ SSH=$(which ssh)
 SSHKEYGEN=$(which ssh-keygen)
 SSSH="::::"
 
-echo "${SSSH} Sam's SSH Wrapper by sam.k.tan"
+# print a banner message
+echo "${SSSH} Sam's SSH Wrapper by sam.k.tan@oracle.com"
 
 # run SSH with the given parameters
 ${SSH} ${PARAMS}
 
-# if SSH exits with status code 255 ...
-if [ $? -eq 255 ]; then
-	# extract the hostname from the SSH parameters
-	HOST=$(${SSH} -G ${PARAMS} | grep -i '^hostname' | cut -d ' '  -f2)
+# if SSH exits with status code other than 255 ...
+[ $? -ne 255 ] && exit $?
 
-	# check if hostname exists in known_hosts file
-	${SSHKEYGEN} -F ${HOST} > /dev/null 2>&1
+# extract the hostname from the SSH parameters
+HOST=$(${SSH} -G ${PARAMS} | grep -i '^hostname' | cut -d ' '  -f2)
 
-	# if hostname does not exist, then exit
-	if [ $? -eq 1 ]; then
-		exit 255
-	fi
+# check if hostname exists in known_hosts file
+${SSHKEYGEN} -F ${HOST} > /dev/null 2>&1
 
-	# since hostname exists, ask to delete and try again
-	echo "${SSSH} Matching hostname found in known_hosts file."
-	echo "${SSSH} Do you want to remove the offending host key(s) and retry the connection?"
-	echo "${SSSH} Only YES is accepted, any other key to cancel."
-	read RESPONSE
+# if hostname does not exist, then exit
+[ $? -ne 0 ] && exit 255
 
-	if [ "xx${RESPONSE}xx" == "xxYESxx" ]; then
-		echo "${SSSH} Removing offending keys ..."
-		${SSHKEYGEN} -R ${HOST}
+# since hostname exists, ask to delete and try again
+echo "${SSSH} Matching hostname found in known_hosts file."
+echo "${SSSH} Do you want to remove the offending host key(s) and retry the connection?"
+echo "${SSSH} Only YES is accepted, any other key to cancel."
+read RESPONSE
 
-		echo "${SSSH} Retrying SSH ..."
-		${SSH} ${PARAMS}
-	else
-		echo "${SSSH} Exiting ... no changes made."
-	fi
-fi
+# if user entered anything other than YES
+[ "x${RESPONSE}x" != "xYESx" ] && return 255
+
+# remove the existing host keys
+echo "${SSSH} Removing offending keys ..."
+${SSHKEYGEN} -R ${HOST}
+
+# retry the SSH command with the given parameters
+echo "${SSSH} Retrying SSH ..."
+${SSH} ${PARAMS}
 
